"""
Constants for Project Narco-Syndicate Pygame UI.
Split from app.py for modularity.
"""

# Screen dimensions
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768

# Frames per second
FPS = 60

# Upgrade item dimensions and positions
UPGRADE_ITEM_X_START = 50
UPGRADE_ITEM_WIDTH = SCREEN_WIDTH - 2 * UPGRADE_ITEM_X_START
UPGRADE_BUTTON_WIDTH = 170
UPGRADE_BUTTON_HEIGHT = 40

# Prompt duration
PROMPT_DURATION_FRAMES = 120

from .ui_theme import (
    FONT_XLARGE, FONT_LARGE, FONT_MEDIUM, FONT_SMALL, FONT_XSMALL, FONT_LARGE_BOLD,
    RICH_BLACK, OXFORD_BLUE, YALE_BLUE, SILVER_LAKE_BLUE, PLATINUM, GHOST_WHITE,
    IMPERIAL_RED, EMERALD_GREEN, GOLDEN_YELLOW, NEON_BLUE,
    DARK_GREY, MEDIUM_GREY, LIGHT_GREY, VERY_LIGHT_GREY,
    BUTTON_COLOR, BUTTON_HOVER_COLOR, BUTTON_DISABLED_COLOR,
    BUTTON_TEXT_COLOR, BUTTON_DISABLED_TEXT_COLOR, TEXT_COLOR,
    TEXT_INPUT_BG_COLOR, TEXT_INPUT_BORDER_COLOR, TEXT_INPUT_TEXT_COLOR,
    HUD_BACKGROUND_COLOR, HUD_TEXT_COLOR, HUD_ACCENT_COLOR,
    draw_text, draw_panel, draw_input_box
)
