from enum import Enum

class DrugQuality(Enum):
    CUT = 1
    STANDARD = 2
    PURE = 3

class DrugName(Enum):
    WEED = "Weed"
    PILLS = "Pills"
    COKE = "Coke"
    SPEED = "Speed"
    HEROIN = "Heroin"

class RegionName(Enum):
    DOWNTOWN = "Downtown"
    SUBURBS = "Suburbs"
    INDUSTRIAL = "Industrial District"
    DOCKS = "Docks"
    COMMERCIAL = "Commercial District"

class CryptoCoin(Enum):
    BITCOIN = "Bitcoin"
    ETHEREUM = "Ethereum"
    MONERO = "Monero"
    ZCASH = "ZCash"
    DRUG_COIN = "DrugCoin"

class SkillID(Enum):
    MARKET_INTUITION = "MARKET_INTUITION"
    DIGITAL_FOOTPRINT = "DIGITAL_FOOTPRINT"
    COMPARTMENTALIZATION = "COMPARTMENTALIZATION"
    GHOST_PROTOCOL = "GHOST_PROTOCOL"
    MARKET_ANALYST = "MARKET_ANALYST"
    GHOST_NETWORK_ACCESS = "GHOST_NETWORK_ACCESS"

class EventType(Enum):
    DEMAND_SPIKE = "DEMAND_SPIKE"
    SUPPLY_DISRUPTION = "SUPPLY_DISRUPTION"
    POLICE_CRACKDOWN = "POLICE_CRACKDOWN"
    CHEAP_STASH = "CHEAP_STASH"
    THE_SETUP = "THE_SETUP"
    RIVAL_BUSTED = "RIVAL_BUSTED"
    DRUG_MARKET_CRASH = "DRUG_MARKET_CRASH"
    MUGGING = "MUGGING"
    INFORMANT_BETRAYAL = "INFORMANT_BETRAYAL"
    BLACK_MARKET_OPPORTUNITY = "BLACK_MARKET_OPPORTUNITY"
    FORCED_FIRE_SALE = "FORCED_FIRE_SALE"
